app:
  replicas: 4
  image: thiernos/ui
  imagePullPolicy: IfNotPresent
  env: prod
  computeres:
    limits:
      cpu: 0.5
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 2Gi

service:
  type: NodePort
  port: 8081
  targetport: 8081

container:
  name: react-ui
  
hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 4
  targetCPUUtilizationPercentage: 50


